/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Valentina Bustamante
 */
public class NEXTLEVEL extends javax.swing.JFrame {

    /**
     * Creates new form NEXTLEVEL
     */
    public NEXTLEVEL() {
        initComponents();
        lev_2.setVisible(false);
        lev_3.setVisible(false);
        this.setLocationRelativeTo(null);
        advertencia.setVisible(false);
        score.setText(String.valueOf(HOMEE.Ranking[HOMEE.jugadores][0]));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        score = new javax.swing.JLabel();
        lev_1 = new javax.swing.JLabel();
        lev_2 = new javax.swing.JLabel();
        lev_3 = new javax.swing.JLabel();
        advertencia = new javax.swing.JLabel();
        bgnextlevel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 400));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        score.setFont(new java.awt.Font("Consolas", 1, 48)); // NOI18N
        score.setForeground(new java.awt.Color(31, 39, 27));
        score.setText("000");
        getContentPane().add(score, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 260, -1, -1));

        lev_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pfmedia/level1bt.png"))); // NOI18N
        lev_1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lev_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lev_1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lev_1MouseExited(evt);
            }
        });
        getContentPane().add(lev_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, 90, 90));

        lev_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pfmedia/level2bt.png"))); // NOI18N
        lev_2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lev_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lev_2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lev_2MouseExited(evt);
            }
        });
        getContentPane().add(lev_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 360, 90, 90));

        lev_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pfmedia/level3bt.png"))); // NOI18N
        lev_3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lev_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lev_3MouseClicked(evt);
            }
        });
        getContentPane().add(lev_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 360, 90, 90));

        advertencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pfmedia/advertencianivel.png"))); // NOI18N
        getContentPane().add(advertencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 460, 460, 30));

        bgnextlevel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pfmedia/nextlevelbg.png"))); // NOI18N
        bgnextlevel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                bgnextlevelMouseMoved(evt);
            }
        });
        getContentPane().add(bgnextlevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 701, 401));

        jPanel1.setBackground(new java.awt.Color(31, 39, 27));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved

    }//GEN-LAST:event_formMouseMoved

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        if (NIVEL1.nivel1 == true) {
            lev_2.setVisible(true);
        }

        if (NIVEL2.nivel2 == true) {
            lev_3.setVisible(true);
            lev_2.setVisible(true);
        }
    }//GEN-LAST:event_formWindowActivated

    private void bgnextlevelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgnextlevelMouseMoved

    }//GEN-LAST:event_bgnextlevelMouseMoved

    private void lev_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lev_2MouseClicked
        if (NIVEL2.nivel2 == false) {
            NIVEL2 abrir = new NIVEL2();
            abrir.setVisible(true);

            NIVEL1 cerrar = new NIVEL1();
            cerrar.setVisible(false);

            NIVEL3 cerrar1 = new NIVEL3();
            cerrar1.setVisible(false);

            this.setVisible(false);
        } else {
            advertencia.setVisible(true);
        }

    }//GEN-LAST:event_lev_2MouseClicked

    private void lev_3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lev_3MouseClicked

        NIVEL2 cerrar1 = new NIVEL2();
        cerrar1.setVisible(false);

        NIVEL1 cerrar = new NIVEL1();
        cerrar.setVisible(false);
        NIVEL3 abrir = new NIVEL3();
        abrir.setVisible(true);

        this.setVisible(false);
    }//GEN-LAST:event_lev_3MouseClicked

    private void lev_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lev_1MouseClicked
        advertencia.setVisible(true);
    }//GEN-LAST:event_lev_1MouseClicked

    private void lev_2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lev_2MouseExited
        advertencia.setVisible(false);
    }//GEN-LAST:event_lev_2MouseExited

    private void lev_1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lev_1MouseExited
        advertencia.setVisible(false);
    }//GEN-LAST:event_lev_1MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NEXTLEVEL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NEXTLEVEL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NEXTLEVEL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NEXTLEVEL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NEXTLEVEL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel advertencia;
    private javax.swing.JLabel bgnextlevel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lev_1;
    private javax.swing.JLabel lev_2;
    private javax.swing.JLabel lev_3;
    private javax.swing.JLabel score;
    // End of variables declaration//GEN-END:variables
}
